// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0SMNg-JNLZqmzaYj9K3mr5nKXD0eno_0',
    appId: '1:311526100903:web:ef8db383f684cd2fbbf082',
    messagingSenderId: '311526100903',
    projectId: 'talenthub-2375d',
    authDomain: 'talenthub-2375d.firebaseapp.com',
    storageBucket: 'talenthub-2375d.appspot.com',
    measurementId: 'G-PVPF686XDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWHYICudqHH_4F5dYXCVdddEJwsEG5bs',
    appId: '1:311526100903:android:a9e33407385d4c89bbf082',
    messagingSenderId: '311526100903',
    projectId: 'talenthub-2375d',
    storageBucket: 'talenthub-2375d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvS5nLmgIhEtokm3_EerOsdOduNBcxBWc',
    appId: '1:311526100903:ios:f5ffaa7e195d4b27bbf082',
    messagingSenderId: '311526100903',
    projectId: 'talenthub-2375d',
    storageBucket: 'talenthub-2375d.appspot.com',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvS5nLmgIhEtokm3_EerOsdOduNBcxBWc',
    appId: '1:311526100903:ios:6f663d3ca5daa8afbbf082',
    messagingSenderId: '311526100903',
    projectId: 'talenthub-2375d',
    storageBucket: 'talenthub-2375d.appspot.com',
    iosBundleId: 'com.example.portfolioApp.RunnerTests',
  );
}
